version: 2.1

orbs:
  # The maven orb contains a set of prepackaged circleci configuration you can use
  # Orbs commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  maven: circleci/maven@1.0

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      # Be sure to change this to major.minor version of java you need to support.
      - image: cimg/openjdk:11.0
    # Checkout the code as the first step.
    # The java orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    # Here we're making sure we just pip by default
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: Build
                command: mvn -B -DskipTests clean package
            - run:
                name: Test
                command: mvn test


